FROM node:13-slim

# This is require for the webpack plugins that convert images to webp
# RUN  apt install libgl1-mesa-glx

# Set environnement to development
ENV NODE_ENV=development

# Change for app directory
WORKDIR /node/app

# Copy npm dependencies
COPY --chown=node:node package*.json yarn.lock* ./

# Create app directory to contain the app and set permission for node user
RUN chown -R node:node .

# Change the user to be node
USER node

# Install dependencies
RUN yarn install && yarn cache clean

# Add to PATH
RUN npm config set scripts-prepend-node-path true

# Copy existing local files into container, and set permission to node user
COPY --chown=node:node  . .

# Use your dev command described in package.json
CMD [ "yarn", "dev" ]